project:
  type: book

book:
  title: "Learning Dairy"
  author: "Xiaoyun Gong"
  date: "2024/2/1"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

